# Generated by Django 5.0.6 on 2024-07-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_school_it',
            field=models.BooleanField(default=False),
        ),
    ]
