# Generated by Django 5.0.6 on 2024-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='key',
            field=models.CharField(default='DEFAULT_KEY', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='date_of_procurement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
    ]
