# Generated by Django 5.0.6 on 2024-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0002_accesskey_key_alter_accesskey_date_of_procurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
